### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by cannatag** [tessera-metrics/tessera#534]
Is this project still alive?

**Comment by aalpern** [comment]
@cannatag Original author here - I don't believe anyone at UA is maintaining this repo anymore (I no longer work there as of late last year). I'm maintaining and enhancing [my fork](https://github.com/aalpern/tessera), although progress has been slow since it's not part of my day-to-day work at the moment.

**Comment by cannatag** [comment]
Thanks, I'll check your fork. Tessera is an excellent tool for visualization. I used it a lot.

**Comment by aalpern** [comment]
Good news - the original repo is now part of the [tessera-metrics](https://github.com/tessera-metrics) github org, so I'll be working to merge my bug fixes and updates back in here and put together an updated roadmap for future improvements.

**Comment by cannatag** [comment]
This is a good news. Thanks!
